
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch main
# Your branch is up to date with 'origin/main'.
#
# Changes to be committed:
#	new file:   .browserslistrc
#	new file:   .gitattributes
#	new file:   .gitignore
#	new file:   .ruby-version
#	new file:   Gemfile
#	new file:   Gemfile.lock
#	new file:   Rakefile
#	new file:   app/assets/config/manifest.js
#	new file:   app/assets/images/.keep
#	new file:   app/assets/stylesheets/application.css
#	new file:   app/assets/stylesheets/scaffolds.scss
#	new file:   app/assets/stylesheets/users.scss
#	new file:   app/channels/application_cable/channel.rb
#	new file:   app/channels/application_cable/connection.rb
#	new file:   app/controllers/application_controller.rb
#	new file:   app/controllers/concerns/.keep
#	new file:   app/controllers/users_controller.rb
#	new file:   app/helpers/application_helper.rb
#	new file:   app/helpers/users_helper.rb
#	new file:   app/javascript/channels/consumer.js
#	new file:   app/javascript/channels/index.js
#	new file:   app/javascript/packs/application.js
#	new file:   app/jobs/application_job.rb
#	new file:   app/mailers/application_mailer.rb
#	new file:   app/models/application_record.rb
#	new file:   app/models/concerns/.keep
#	new file:   app/models/user.rb
#	new file:   app/views/layouts/application.html.erb
#	new file:   app/views/layouts/mailer.html.erb
#	new file:   app/views/layouts/mailer.text.erb
#	new file:   app/views/users/_form.html.erb
#	new file:   app/views/users/_user.json.jbuilder
#	new file:   app/views/users/edit.html.erb
#	new file:   app/views/users/index.html.erb
#	new file:   app/views/users/index.json.jbuilder
#	new file:   app/views/users/new.html.erb
#	new file:   app/views/users/show.html.erb
#	new file:   app/views/users/show.json.jbuilder
#	new file:   babel.config.js
#	new file:   bin/bundle
#	new file:   bin/rails
#	new file:   bin/rake
#	new file:   bin/setup
#	new file:   bin/spring
#	new file:   bin/webpack
#	new file:   bin/webpack-dev-server
#	new file:   bin/yarn
#	new file:   config.ru
#	new file:   config/application.rb
#	new file:   config/boot.rb
#	new file:   config/cable.yml
#	new file:   config/credentials.yml.enc
#	new file:   config/database.yml
#	new file:   config/environment.rb
#	new file:   config/environments/development.rb
#	new file:   config/environments/production.rb
#	new file:   config/environments/test.rb
#	new file:   config/initializers/application_controller_renderer.rb
#	new file:   config/initializers/assets.rb
#	new file:   config/initializers/backtrace_silencers.rb
#	new file:   config/initializers/content_security_policy.rb
#	new file:   config/initializers/cookies_serializer.rb
#	new file:   config/initializers/filter_parameter_logging.rb
#	new file:   config/initializers/inflections.rb
#	new file:   config/initializers/mime_types.rb
#	new file:   config/initializers/permissions_policy.rb
#	new file:   config/initializers/wrap_parameters.rb
#	new file:   config/locales/en.yml
#	new file:   config/puma.rb
#	new file:   config/routes.rb
#	new file:   config/spring.rb
#	new file:   config/storage.yml
#	new file:   config/webpack/development.js
#	new file:   config/webpack/environment.js
#	new file:   config/webpack/production.js
#	new file:   config/webpack/test.js
#	new file:   config/webpacker.yml
#	new file:   db/migrate/20211225214938_create_users.rb
#	new file:   db/schema.rb
#	new file:   db/seeds.rb
#	new file:   id_rsa.pub
#	new file:   lib/assets/.keep
#	new file:   lib/tasks/.keep
#	new file:   log/.keep
#	new file:   package.json
#	new file:   postcss.config.js
#	new file:   public/404.html
#	new file:   public/422.html
#	new file:   public/500.html
#	new file:   public/apple-touch-icon-precomposed.png
#	new file:   public/apple-touch-icon.png
#	new file:   public/favicon.ico
#	new file:   public/robots.txt
#	new file:   storage/.keep
#	new file:   test/application_system_test_case.rb
#	new file:   test/channels/application_cable/connection_test.rb
#	new file:   test/controllers/.keep
#	new file:   test/controllers/users_controller_test.rb
#	new file:   test/fixtures/files/.keep
#	new file:   test/fixtures/users.yml
#	new file:   test/helpers/.keep
#	new file:   test/integration/.keep
#	new file:   test/mailers/.keep
#	new file:   test/models/.keep
#	new file:   test/models/user_test.rb
#	new file:   test/system/.keep
#	new file:   test/system/users_test.rb
#	new file:   test/test_helper.rb
#	new file:   tmp/.keep
#	new file:   tmp/pids/.keep
#	new file:   vendor/.keep
#	new file:   yarn.lock
#

